Feature/passing direct url and local path to agent runner epmdj 10700
Drill4J/agent-runner pull request #12
Opened 2023-11-01 17:45 UTC by bodyangug

2023-11-02 11:52 UTC, RomanDavlyatshin requested changes

2023-11-02 11:52 UTC, RomanDavlyatshin commented on common/src/main/kotlin/AgentLoader.kt
>      }
```
    fun downloadAgent(
        config: Configuration,
        dir: File
    ) = run {
        var file: File
        val artName = "${config.artifactId}-$presetName-${config.version}.zip"

        if (config.directLocalPathToZip != null) {
            println("Download agent: from local path ${config.directLocalPathToZip}")
            file = dir.resolve(config.directLocalPathToZip)
        } else if (config.directUrlToZip != null) {
            println("Download agent: from direct url ${config.directUrlToZip}")
            file = dir.resolve(artName)
            file.ensureFile(URL(config.directUrlToZip))
        } else {
            val artPath = "${config.repositoryName}/releases/download/v${config.version}/$artName"
            val urlToDownload = "${GITHUB_URL.replace("api.", "")}/$DRILL_OWNER/$artPath"
            println("Download agent: from default repository $urlToDownload")
            file = dir.resolve(artName)
            file.ensureFile(URL(urlToDownload))
        }

        unzip(file, dir)
    }
```
TODO - add error handling

2023-11-02 11:52 UTC, RomanDavlyatshin commented on common/src/main/kotlin/AgentLoader.kt
> +    private fun File.ensureFile(downloadFrom: URL) {
Misleading function name - it also downloads file

2023-11-02 11:52 UTC, RomanDavlyatshin commented on common/src/main/kotlin/AgentLoader.kt
>      }
```
    fun downloadAgent(
        config: Configuration,
        dir: File
    ) = run {
        var zipPath: File
        if (config.directLocalPathToZip != null) {
            zipPath = dir.resolve(config.directLocalPathToZip)
        } else {
            val url = config.directUrlToZip ?: getDefaultRepositoryUrl(config)
            val bytes = URL(url).openStream().readBytes()
            zipPath = dir.resolve(getArtifactName(config))
            zipPath.createNewFile()
            zipPath.writeBytes(bytes)
        }
        unzip(zipPath, dir)
    }

    private fun  getDefaultRepositoryUrl (config: Configuration) =
        "${GITHUB_URL.replace("api.", "")}/$DRILL_OWNER/" +
                "${config.repositoryName}/releases/download/v" +
                "${config.version}/${getArtifactName(config)}"
    private fun getArtifactName (config: Configuration) = "${config.artifactId}-$presetName-${config.version}.zip" }
```

2023-11-02 12:54 UTC, bodyangug commented on common/src/main/kotlin/AgentLoader.kt
> +        lateinit var file: File
removed

2023-11-02 12:54 UTC, bodyangug commented on common/src/main/kotlin/AgentLoader.kt
> +        if (directUrlToZip != null && directLocalPathToZip == null) {
reworked

2023-11-02 12:54 UTC, bodyangug commented on common/src/main/kotlin/AgentLoader.kt
> +        // Case 2. directUrlToZip prop is setting-up
removed

2023-11-02 12:55 UTC, bodyangug commented on common/src/main/kotlin/AgentLoader.kt
> +            println("Local path is: $directLocalPathToZip")
reworked

2023-11-02 12:55 UTC, bodyangug commented on common/src/main/kotlin/AppAgentConfiguration.kt
>      override val repositoryName: String = "java-agent"
these two lines was removed

2023-11-02 12:55 UTC, bodyangug commented on common/src/main/kotlin/AgentLoader.kt
>      }
done

2023-11-02 12:56 UTC, bodyangug commented on common/src/main/kotlin/AgentLoader.kt
> +    private fun File.ensureFile(downloadFrom: URL) {
removed

2023-11-02 14:10 UTC, RomanDavlyatshin commented on common/src/main/kotlin/AgentLoader.kt
> +        println("Catch exception. Cause: ${it.cause}. Message: ${it.message}")
according to kotlin docs printstacktrace is only available in kotlin native https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/

2023-11-02 14:14 UTC, bodyangug commented on common/src/main/kotlin/AgentLoader.kt
> +        println("Catch exception. Cause: ${it.cause}. Message: ${it.message}")
done

2023-11-03 10:52 UTC, RomanDavlyatshin approved these changes

2023-11-03 10:54 UTC, merged